# Generated by Django 6.0.3 on 2026-03-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectplace',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='travelproject',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='projectplace',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='projectplace',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='projectplace',
            constraint=models.UniqueConstraint(fields=('project', 'external_id'), name='unique_place_per_project'),
        ),
    ]
